name = "hemodialisis-app"
compatibility_date = "2024-01-01"

[env.production]
name = "hemodialisis-app-prod"

[[env.production.d1_databases]]
binding = "DB"
database_name = "hemodialisis"
database_id = ""
preview_database_id = ""

[build]
command = "npm run build"
cwd = ""
watch_dir = ""

[[pages_build_output_dir]]
output_dir = "public"

[vars]
ENVIRONMENT = "production"
